apiVersion: v1
kind: Service
metadata:
  name: rclone
  labels:
    app.kubernetes.io/name: rclone
    app.kubernetes.io/component: sftp-server
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 2022
      protocol: TCP
      targetPort: 2022
  selector:
    app.kubernetes.io/name: rclone
    app.kubernetes.io/component: sftp-server
