---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "~6.48.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    plugins:
      - grafana-piechart-panel
    sidecar:
      dashboards:
        enabled: true
    grafana.ini:
      "auth.anonymous":
        enabled: true

