apiVersion: v1
kind: Service
metadata:
  name: veidemann-robotsevaluator-service
  labels:
    app.kubernetes.io/name: veidemann-robotsevaluator
    app.kubernetes.io/component: robotsevaluator
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 7053
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: veidemann-robotsevaluator
    app.kubernetes.io/component: robotsevaluator
