apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/instance: veidemann-warcvalidator
  app.kubernetes.io/part-of: veidemann
