apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-harvester
spec:
  template:
    spec:
      containers:
        - name: veidemann-browser-controller
          env:
            - name: PROXY_COUNT
              value: "5"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: DB_USE_OPENTRACING
              value: "true"
        - name: veidemann-harvester-proxy
          env:
            - name: LOG_LEVEL
              value: "warn"
            - name: PROXY_COUNT
              value: "5"
