apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-metrics
  labels:
    app.kubernetes.io/name: veidemann-metrics
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-metrics
      app.kubernetes.io/component: metrics
  template:
    metadata:
      name: veidemann-metrics
      labels:
        app.kubernetes.io/name: veidemann-metrics
        app.kubernetes.io/component: metrics
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: veidemann-metrics
          image: norsknettarkiv/veidemann-metrics:v0.3.1
          ports:
            - containerPort: 9301
              name: http-metrics
              protocol: TCP
          envFrom:
            - secretRef:
                name: rethinkdb-env
                optional: false
          env:
            - name: PORT
              value: "9301"
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: FRONTIER_HOST
              value: "veidemann-frontier"
            - name: FRONTIER_PORT
              value: "7700"
