scyllaImage:
  tage: 4.4.4


agentImage:
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.5.1

datacenter: dc1

racks:
  - name: "rac1"
    members: 1
    storage:
      capacity: 1Gi
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 1Gi
