apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-traefik

resources:
  - ../../../bases/traefik

configMapGenerator:
  - name: traefik-dynamic-config
    behavior: replace
    files:
      - traefik.yaml=traefik-dynamic-config.yaml

patchesStrategicMerge:
  - traefik-deployment-patch.yaml
