kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - crd.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - operator.yaml

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/instance: redis-veidemann
  app.kubernetes.io/component: redis
  app.kubernetes.io/part-of: veidemann
