apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-harvester
  labels:
    app.kubernetes.io/name: veidemann-harvester
    app.kubernetes.io/component: harvester
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-harvester
      app.kubernetes.io/component: harvester
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-harvester
        app.kubernetes.io/component: harvester
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-inbound-ports: "9301"
        config.linkerd.io/skip-outbound-ports: 3128,14250
    spec:
      volumes:
        - name: veidemann-config
          configMap:
            name: veidemann
            items:
              - key: log4j2.xml
                path: log4j2.xml
        - name: workdir
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: cache-certificate
          secret:
            secretName: veidemann-cache
      terminationGracePeriodSeconds: 30
      containers:
        - name: veidemann-harvester
          image: norsknettarkiv/veidemann-harvester:0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: proxy
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 9301
              protocol: TCP
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: BROWSER_WS_ENDPOINT
              value: ws://localhost:3000/?--proxy-server=localhost:8080
            - name: MAX_OPEN_SESSIONS
              value: "2"
            - name: PROXY_HOST
              value: localhost
            - name: PROXY_PORT
              value: "9900"
            - name: FRONTIER_HOST
              value: veidemann-frontier
            - name: FRONTIER_PORT
              value: "7700"
            - name: CONTENT_WRITER_HOST
              value: "veidemann-contentwriter"
            - name: CONTENT_WRITER_PORT
              value: "8082"
            - name: ROBOTS_EVALUATOR_HOST
              value: "veidemann-robotsevaluator-service"
            - name: ROBOTS_EVALUATOR_PORT
              value: "7053"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-harvester-controller
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: probabilistic
            - name: JAEGER_SAMPLER_PARAM
              value: "0.1"
            - name: JAVA_TOOL_OPTIONS
              value: -Dfile.encoding=UTF-8
            - name: JAEGER_PROPAGATION
              value: jaeger,b3
          volumeMounts:
            - mountPath: /veidemann/config/log4j2.xml
              name: veidemann-config
              subPath: log4j2.xml
            - mountPath: /workdir
              name: workdir
            - mountPath: /ca-certificates
              name: cache-certificate
              readOnly: true
        - name: veidemann-harvester-proxy
          image: norsknettarkiv/veidemann-recorderproxy:0.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9900
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "9900"
            - name: BROWSER_CONTROLLER_PORT
              value: "9999"
            - name: PROXY_COUNT
              value: "2"
            - name: DNS_RESOLVER_HOST
              value: "veidemann-dns-resolver"
            - name: DNS_RESOLVER_PORT
              value: "8053"
            - name: CONTENT_WRITER_HOST
              value: "veidemann-contentwriter"
            - name: CONTENT_WRITER_PORT
              value: "8082"
            - name: CACHE_HOST
              value: "veidemann-cache-balancer"
            - name: CACHE_PORT
              value: "3128"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-harvester-proxy
            - name: JAEGER_PROPAGATION
              value: jaeger,b3
        - name: veidemann-harvester-browser
          image: browserless/chrome:1.18.1-puppeteer-1.20.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: debug
              protocol: TCP
          env:
            - name: CONNECTION_TIMEOUT
              value: "600000"
            - name: ENABLE_CORS
              value: "true"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-harvester-browser
            - name: JAEGER_PROPAGATION
              value: jaeger,b3
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /json/version
              port: debug
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /json/version
              port: debug
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
