apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb-admin
  labels:
    app.kubernetes.io/component: admin
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: admin
  template:
    metadata:
      name: rethinkdb-admin
      labels:
        app.kubernetes.io/component: admin
    spec:
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb-admin
          image: rethinkdb-cluster
          imagePullPolicy: IfNotPresent
          ports:
            - name: cluster
              containerPort: 29015
            - name: driver
              containerPort: 28015
            - name: http-admin
              containerPort: 8080
          args:
            - --bind
            - $(POD_IP)
            - --no-update-check
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: $(RETHINK_CLUSTER_SERVICE_NAME)
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: secrets
          secret:
            secretName: rethinkdb
