apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-admin
  labels:
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-admin
  selector:
    app.kubernetes.io/component: admin
