---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  values:
    nodeSelector:
      ingress-ready: "true"
    updateStrategy:
      type: RollingUpdate
