apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/kube-prometheus
  - ingressroute.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-serviceMonitorVeidemann.yaml
  - prometheus-serviceMonitorRedis.yaml

patchesStrategicMerge:
  - prometheus_patch.yaml
  - alertmanager_alertmanager_patch.yaml

secretGenerator:
  - name: grafana-config
    namespace: monitoring
    files:
      - grafana.ini
