apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
spec:
  template:
    spec:
      containers:
        - name: redis-operator
          env:
            - name: WATCH_NAMESPACE
              value: "veidemann"
              valueFrom: # unset from base
