apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-health-check-api
  labels:
    app.kubernetes.io/name: veidemann-health-check-api
    app.kubernetes.io/component: health-check
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-health-check-api
      app.kubernetes.io/component: health-check
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-health-check-api
        app.kubernetes.io/component: health-check
    spec:
      volumes:
        - name: versions
          configMap:
            name: veidemann-version
            items:
              - key: versions.json
                path: versions.json
      containers:
        - name: veidemann-health-check-api
          image: norsknettarkiv/veidemann-health-check-api:v0.5.0
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          env:
            - name: CONTROLLER_HOST
              value: "veidemann-controller"
            - name: CONTROLLER_PORT
              value: "7700"
            - name: CONTROLLER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: veidemann-health-check-api
                  key: CONTROLLER_API_KEY
                  optional: false
            - name: PROMETHEUS_URL
              value: "http://prometheus-k8s.monitoring:9090"
          volumeMounts:
            - mountPath: /versions.json
              subPath: versions.json
              name: versions
