apiVersion: v1
kind: Service
metadata:
  name: veidemann-health-check-api
  labels:
    app.kubernetes.io/name: veidemann-health-check-api
    app.kubernetes.io/component: health-check
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: veidemann-health-check-api
    app.kubernetes.io/component: health-check
