kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: scylla
    files:
      - ready-probe.sh
      - cassandra-rackdc.properties

vars:
  - name: NAME
    objref:
      kind: Service
      name: scylla
      apiVersion: v1
    fieldref:
       fieldpath: metadata.name
  - name: NAMESPACE
    objref:
      kind: StatefulSet
      name: scylla
      apiVersion: v1
      group: apps
    fieldref:
      fieldpath: metadata.namespace
