apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scylla
  name: scylla
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
    - port: 19042
      name: cql-shard-aware
    - port: 9180
      name: http-metrics
    - name: intra-node
      port: 7000
    - name: tls-intra-node
      port: 7001
    - name: jmx
      port: 7199
  selector:
    app.kubernetes.io/name: scylla
