apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scylla
  name: scylla
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cluster
    - port: 19042
      name: cluster-shard
    - port: 9180
      name: http-metrics
  selector:
    app.kubernetes.io/name: scylla
