apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dex

resources:
  - ../../../bases/dex
  - ingressroute.yaml

secretGenerator:
  - name: dex
    behavior: replace
    files:
      - config.yaml
