apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  externalUrl: https://veidemann.local/prometheus
  enableAdminAPI: true
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  retention: 1d
  retentionSize: 1GB
