apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
