apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: rethinkdb
  app.kubernetes.io/part-of: veidemann

resources:
  - cluster/
  - admin/
  - proxy/
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml

vars:
  - name: RETHINK_CLUSTER_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: rethinkdb-cluster
    fieldref:
      fieldpath: metadata.name

secretGenerator:
  - name: rethinkdb
    literals:
      - rethinkdb-password=rethinkdb
