apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: rethinkdb
  app.kubernetes.io/version: 2.3.5

bases:
  - cluster
  - admin
  - proxy

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml

images:
  - name: rethinkdb-cluster
    newTag: 0.1.0
    newName: codylundquist/helm-rethinkdb-cluster

vars:
  - name: RETHINK_CLUSTER_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: rethinkdb-cluster
    fieldref:
      fieldpath: metadata.name

secretGenerator:
  - name: rethinkdb
    literals:
      - rethinkdb-password=rethinkdb
