apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rethinkdb
subjects:
  - kind: ServiceAccount
    name: rethinkdb
