apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scylla
spec:
  timeout: 2m
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: scylla
      sourceRef:
        kind: HelmRepository
        name: scylla-operator
        namespace: scylla-operator
      version: "~1.8.0"
  values:

    scyllaImage:
      tag: 4.6.11
    # Allows to customize Scylla image
    agentImage:
      tag: 3.0.2
    # Developer mode
    developerMode: true
    # Name of datacenter
    datacenter: "dc1"
    # List of racks
    racks:
      - name: "rac1"
        scyllaConfig: ""
        scyllaAgentConfig: ""
        members: 1
        storage:
          capacity: 1Gi
        resources:
          limits:
            cpu: 500m
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 3Gi
