apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-cache
  labels:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-cache
      app.kubernetes.io/component: cache-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-cache
        app.kubernetes.io/component: cache-balancer
      annotations:
        config.linkerd.io/opaque-ports: "3128"
    spec:
      serviceAccountName: veidemann-cache
      securityContext:
        fsGroup: 13
      containers:
        - name: veidemann-cache
          image: ghcr.io/nlnwa/veidemann-cache:0.3.0
          args:
            - -b # be a balancer
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          env:
            - name: DNS_SERVERS
              value: veidemann-dns-resolver
            - name: SERVICE_NAME
              value: veidemann-cache
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 500Mi
        - name: veidemann-cache-exporter
          image: boynux/squid-exporter:v1.10.3
          ports:
            - name: http-metrics
              containerPort: 9301
              protocol: TCP
          args:
            - "-listen"
            - "0.0.0.0:9301"
