---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: veidemann-cache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: veidemann-cache
  labels:
    app.kubernetes.io/name: veidemann-cache
rules:
  - apiGroups: [""]
    resources: ["endpoints", "service"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: veidemann-cache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: veidemann-cache
subjects:
  - kind: ServiceAccount
    name: veidemann-cache
