apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/jaeger`)
      kind: Rule
      services:
        - name: jaeger-query
          port: 16686
  tls: {}
