apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  annotations:
    linkerd.io/inject: enabled
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /jaeger
  storage:
    type: memory
    options:
      memory:
        max-traces: 1000
  ingress:
    enabled: false
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 0.1
