apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: veidemann-cache
spec:
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 150Mi

