apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: veidemann-cache
spec:
  template:
    spec:
      containers:
        - name: veidemann-cache
          resources:
            requests:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
