apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: veidemann-cache
spec:
  template:
    spec:
      volumes:
        - name: squid-conf-template
          configMap:
            name: squid-conf-template
            items:
              - key: squid.conf.template
                path: squid.conf.template
      containers:
        - name: veidemann-cache
          volumeMounts:
            - name: squid-conf-template
              mountPath: /etc/squid/squid.conf.template
              subPath: squid.conf.template
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 150Mi

