apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/veidemann-cache


patchesJson6902:
- target:
    version: v1 # apiVersion
    group: apps
    kind: StatefulSet
    name: veidemann-cache
  patch: |
    - op: remove
      path: "/spec/template/spec/volumes/3"

patchesStrategicMerge:
  - cache_volume_patch.yaml
  - cache_resources_patch.yaml


configMapGenerator:
  - name: squid-conf-template
    files:
      - squid.conf.template
