---
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: scylla-operator
  namespace: scylla-operator
spec:
  interval: 30m
  url: https://scylla-operator-charts.storage.googleapis.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scylla-operator
  namespace: scylla-operator
spec:
  timeout: 2m
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: scylla-operator
      sourceRef:
        kind: HelmRepository
        name: scylla-operator
        namespace: scylla-operator
      version: "~1.8.0"
  values:
    replicas: 1
    webhookServerReplicas: 1
