---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  interval: 30m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  timeout: 2m
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress-traefik
      version: "~20.8.0"
  values:
    updateStrategy:
      type: Recreate
      rollingUpdate: # unset
    additionalArguments:
      - "--api.insecure=true"
    ingressRoute:
      dashboard:
        entryPoints:
          - websecure
        matchRule: Host(`traefik.veidemann.test`)
    logs:
      access:
        # To enable access logs
        enabled: true

    service:
      type: ClusterIP

    # Configure ports
    ports:
      web:
        hostPort: 80
        expose: true
        redirectTo: websecure
      websecure:
        hostPort: 443
        expose: true
    # Don't check for new version and don't send anonymous usage metrics
    globalArguments: { }
    #  - "--global.checknewversion"
    #  - "--global.sendanonymoususage"
