kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - crd.yaml
  - role.yaml
  - service.yaml
  - deployment.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/instance: ingress-traefik
  app.kubernetes.io/component: ingress
  app.kubernetes.io/part-of: veidemann

configMapGenerator:
  - name: traefik-static-config
    namespace: ingress-traefik
    files:
      - traefik.yaml=traefik-static-config.yaml
  - name: traefik-dynamic-config
    namespace: ingress-traefik
    files:
      - default.yaml=traefik-dynamic-config.yaml
