apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: 443
  selector:
    app: traefik
    app.kubernetes.io/name: traefik
