apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rethinkdb
      app.kubernetes.io/component: database
  template:
    metadata:
      name: rethinkdb-admin
      labels:
        app.kubernetes.io/name: rethinkdb
        app.kubernetes.io/component: database
      annotations:
        config.linkerd.io/opaque-ports: "28015,29015"
    spec:
      volumes:
        - name: datadir
          emptyDir: { }
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb
          image: ghcr.io/nlnwa/rethinkdb-kubernetes:0.2.0
          ports:
            - name: cluster
              containerPort: 29015
            - name: driver
              containerPort: 28015
            - name: http-admin
              containerPort: 8080
          args:
            - --directory
            - /data/db
            - --bind
            - $(POD_IP)
            - --no-update-check
            - --cores
            - "1"
            - --cache-size
            - "725"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi

          env:
            - name: RETHINKDB_CLUSTER_LABEL_SELECTOR
              value: "app.kubernetes.io/name=rethinkdb,app.kubernetes.io/component=database"
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb-env
                  key: DB_PASSWORD
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          startupProbe:
            exec:
              command:
                - /rethinkdb-probe
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir
              mountPath: /data/db
