apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - priorityclass.yaml
  - deployment.yaml
  - cluster-service.yaml
  - proxy-service.yaml
  - admin-service.yaml

secretGenerator:
  - name: rethinkdb-env
    options:
      disableNameSuffixHash: true
    literals:
      - DB_USER=admin
      - DB_PASSWORD=rethinkdb
