apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-proxy
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: proxy
  annotations:
    config.linkerd.io/opaque-ports: "28015"
spec:
  type: ClusterIP
  ports:
    - name: driver
      port: 28015
      targetPort: driver
  selector:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: database
