apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - health_check_api_ingressroute.yaml
  - ../../../bases/veidemann-health-check-api

patchesStrategicMerge:
  - health_check_api_env_patch.yaml
