issuer: https://veidemann.local/dex
storage:
  config:
    inCluster: true
  type: kubernetes

logger:
  level: debug

web:
  http: 0.0.0.0:5556
  allowedOrigins:
    - https://veidemann.local
    - https://localhost:4200

oauth2:
  alwaysShowLoginScreen: false
  responseTypes:
    - code
    - token
    - id_token
  skipApprovalScreen: true

staticClients:
  - id: veidemann-dashboard
    name: Veidemann Admin Dashboard
    redirectURIs:
      - https://veidemann.local/veidemann
      - https://localhost:4200/veidemann
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  - id: veidemann-cli
    name: Veidemann CLI
    public: true
    secret: cli-app-secret
  - id: veidemann-api
    name: Veidemann API
    secret: VerySecret
    trustedPeers:
      - veidemann-cli
      - veidemann-dashboard

enablePasswordDB: true
staticPasswords:
  - email: admin@example.com
    hash: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
    username: admin
