apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: veidemann-cert
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/tls
    files:
      - tls.key=veidemann.test/key.pem
      - tls.crt=veidemann.test/cert.pem
