apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: veidemann-ingress-tls-cert
    type: kubernetes.io/tls
    files:
      - tls.key=veidemann-local_key.pem
      - tls.crt=veidemann-local_cert.pem
