apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-frontier-queue-workers
  labels:
    app.kubernetes.io/name: veidemann-frontier-queue-workers
    app.kubernetes.io/component: frontier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-frontier-queue-workers
      app.kubernetes.io/component: frontier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-frontier-queue-workers
        app.kubernetes.io/component: frontier
      annotations:
        linkerd.io/inject: enabled
        # Wait 5 seconds before blocking new requests after receiving the TERM signal.
        # It should be enough time to ensure workers have completed.
        # See https://linkerd.io/2.11/tasks/graceful-shutdown/.
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "5"
    spec:
      containers:
        - name: veidemann-frontier-queue-workers
          image: ghcr.io/nlnwa/veidemann-frontier-queue-workers:0.1.0
          envFrom:
            - secretRef:
                name: rethinkdb-env
                optional: false
          env:
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: REDIS_HOST
              value: redis-veidemann-frontier-master
            - name: REDIS_PORT
              value: "6379"
