apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-exporter
  labels:
    app.kubernetes.io/name: rethinkdb-exporter
    app.kubernetes.io/component: metrics
    metrics: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9123
      targetPort: http
  selector:
    app.kubernetes.io/name: rethinkdb-exporter
    app.kubernetes.io/component: metrics
