apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-metrics
  labels:
    app.kubernetes.io/name: veidemann-metrics
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-metrics
      app.kubernetes.io/component: metrics
  template:
    metadata:
      name: veidemann-metrics
      labels:
        app.kubernetes.io/name: veidemann-metrics
        app.kubernetes.io/component: metrics
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: veidemann-metrics
          image: norsknettarkiv/veidemann-metrics:v0.3.0
          ports:
            - containerPort: 9301
              name: http-metrics
              protocol: TCP
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
