apiVersion: v1
kind: Service
metadata:
  name: veidemann-metrics
  labels:
    app.kubernetes.io/name: veidemann-metrics
    app.kubernetes.io/component: metrics
    metrics: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9001
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-metrics
    app.kubernetes.io/component: metrics
