apiVersion: v1
kind: Service
metadata:
  name: veidemann-frontier
  labels:
    app.kubernetes.io/name: veidemann-frontier
    app.kubernetes.io/component: frontier
spec:
  type: ClusterIP
  ports:
    - port: 7700
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: veidemann-frontier
    app.kubernetes.io/component: frontier
