---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rethinkdb
  labels:
    app.kubernetes.io/name: rethinkdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rethinkdb
subjects:
  - kind: ServiceAccount
    name: rethinkdb
