apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - redis-statefulset.yaml
  - redis-svc.yaml
  - redis-headless-svc.yaml
  - redis-master-svc.yaml

configMapGenerator:
  - name: redis-veidemann-frontier-config
    files:
      - redis.conf
