apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    redis: veidemann-frontier
  name: redis-veidemann-frontier
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      redis: veidemann-frontier
  serviceName: redis-veidemann-frontier-headless
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        redis: veidemann-frontier
    spec:
      containers:
      - args:
        - /config/redis.conf
        image: redis:6-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 7777777
          runAsNonRoot: true
          runAsUser: 7777777
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/redis.conf
          name: config
          readOnly: true
          subPath: redis.conf
        - mountPath: /data
          name: data
        workingDir: /data
      - args:
        - --web.listen-address=:9121
        env:
        - name: REDIS_ALIAS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: oliver006/redis_exporter:v1.27.1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9121
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: exporter
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9121
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 7777777
          runAsNonRoot: true
          runAsUser: 7777777
      # initContainers:
      # - args:
      #   - |-
      #     set -e
      #     set -o pipefail

      #     echo never > /rootfs/sys/kernel/mm/transparent_hugepage/enabled

      #     grep -q -F [never] /sys/kernel/mm/transparent_hugepage/enabled
      #   command:
      #   - sh
      #   - -c
      #   image: busybox
      #   imagePullPolicy: Always
      #   name: disable-thp
      #   resources: {}
      #   terminationMessagePath: /dev/termination-log
      #   terminationMessagePolicy: File
      #   volumeMounts:
      #   - mountPath: /rootfs/sys
      #     name: sys
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: redis-veidemann-frontier-config
        name: config
      # - hostPath:
      #     path: /sys
      #     type: ""
      #   name: sys
      - name: data
        emptyDir: {}
  # volumeClaimTemplates:
  # - apiVersion: v1
  #   kind: PersistentVolumeClaim
  #   metadata:
  #     labels:
  #       redis: veidemann-frontier
  #     name: data
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 5Gi
  #     storageClassName: gluster
