apiVersion: v1
kind: Service
metadata:
  labels:
    redis: veidemann-frontier
  name: redis-veidemann-frontier-master
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: exporter
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    redis: veidemann-frontier
  type: ClusterIP
