apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-contentexplorer
  labels:
    app.kubernetes.io/name: veidemann-contentexplorer
    app.kubernetes.io/component: contentexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-contentexplorer
      app.kubernetes.io/component: contentexplorer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-contentexplorer
        app.kubernetes.io/component: contentexplorer
    spec:
      volumes:
        - emptyDir: {}
          name: workdir
        - name: warcs
          emptyDir: {}
        - name: veidemann-config
          configMap:
            name: veidemann
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: veidemann-contentexplorer
          image: norsknettarkiv/veidemann-contentexplorer:0.5.0
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /warcs
              name: warcs
            - mountPath: /veidemann/config/log4j2.xml
              name: veidemann-config
              subPath: log4j2.xml
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
