apiVersion: v1
kind: Service
metadata:
  name: veidemann-contentexplorer
  labels:
    app.kubernetes.io/name: veidemann-contentexplorer
    app.kubernetes.io/component: contentexplorer
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/name: veidemann-contentexplorer
    app.kubernetes.io/component: contentexplorer
