apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-frontier-queue-workers
spec:
  template:
    spec:
      containers:
        - name: veidemann-frontier-queue-workers
          env:
            - name: LOG_LEVEL
              value: "debug"
