apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/veidemann-frontier-queue-workers

patchesStrategicMerge:
  - deployment_env_patch.yaml
