---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-subpath
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "veidemann"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.telemetry.svc.cluster.local:9090/prometheus
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 30s
