---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: veidemann
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - veidemann
  selector:
    matchLabels:
      metrics: prometheus
