apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-warcvalidator-api
  labels:
    app.kubernetes.io/name: veidemann-warcvalidator-api
    app.kubernetes.io/component: warcvalidator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-warcvalidator-api
      app.kubernetes.io/component: warcvalidator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-warcvalidator-api
        app.kubernetes.io/component: warcvalidator
    spec:
      containers:
        - name: veidemann-warcvalidator-api
          image: "norsknettarkiv/veidemann-warcvalidator-api:v0.1.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"

