apiVersion: v1
kind: Service
metadata:
  name: veidemann-warcvalidator-api
  labels:
    app.kubernetes.io/name: veidemann-warcvalidator-api
    app.kubernetes.io/component: warcvalidator
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: veidemann-warcvalidator-api
    app.kubernetes.io/component: warcvalidator

