kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: veidemann-backup
  labels:
    app.kubernetes.io/part-of: veidemann
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
