kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: veidemann-warcs
  labels:
    app.kubernetes.io/part-of: veidemann
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
