apiVersion: batch/v1
kind: Job
metadata:
  name: rethinkdb-backup
  labels:
    app.kubernetes.io/name: rethinkdb-backup
    app.kubernetes.io/component: backup
spec:
  template:
    metadata:
      name: rethinkdb-backup
      labels:
        app.kubernetes.io/name: rethinkdb-backup
        app.kubernetes.io/component: backup
    spec:
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: veidemann-backup
        - name: rethinkdb-password
          secret:
            secretName: rethinkdb-env
            optional: false
            items:
              - key: DB_PASSWORD
                path: rethinkdb-password
        - name: data
          persistentVolumeClaim:
            claimName: veidemann-backup
      containers:
        - name: rethinkdb-backup
          image: ghcr.io/nlnwa/rethinkdb-backup:0.5.0
          env:
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: FILE_PREFIX
              value: "rethinkdb_dump_veidemann"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: rethinkdb-password
              mountPath: /secret
              readOnly: true
          args:
            - dump
            - -e
            - veidemann.config
            - -e
            - veidemann.config_crawl_entities
            - -e
            - veidemann.config_seeds
            - -e
            - veidemann.system
            - --password-file
            - /secret/rethinkdb-password
            - --connect
            - "$(DB_HOST):$(DB_PORT)"
