apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-cache-balancer
spec:
  template:
    spec:
      containers:
        - name: veidemann-cache-balancer
          env:
            - name: DNS_SERVERS
              value: $(DNS_RESOLVER_SERVICE_NAME)
            - name: SERVICE_NAME
              value: $(CACHE_SERVICE_NAME)
