apiVersion: batch/v1
kind: Job
metadata:
  name: veidemann-db-initializer
spec:
  template:
    spec:
      containers:
        - name: veidemann-db-initializer
          env:
            - name: DB_HOST
              value: $(DB_SERVICE_NAME)
