apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-dns-resolver
spec:
  template:
    spec:
      containers:
        - name: veidemann-dns-resolver
          env:
            - name: DB_HOST
              value: $(DB_SERVICE_NAME)
            - name: CONTENT_WRITER_HOST
              value: $(CONTENT_WRITER_SERVICE_NAME)
