apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - redis_distributed_lock.yaml
  - ../../../bases/dex
  - ../../../bases/rethinkdb
  - ../../../bases/veidemann-db-initializer
  - ../../../bases/veidemann-dns-resolver
  - ../../../bases/veidemann-controller
  - ../../../bases/veidemann-frontier
  - ../../../bases/veidemann-contentwriter
  - ../../../bases/veidemann-cache
  - ../../../bases/veidemann-robotsevaluator
  - ../../../bases/veidemann-harvester
  - ../../../bases/veidemann-dashboard
  - ../../../bases/veidemann-warcvalidator
  - ingressroute.yaml

namespace: veidemann

patches:
  - path: controller_ca_patch.yaml
  - path: controller_env_patch.yaml
  - path: db-initializer_env_patch.yaml
  - path: frontier_env_patch.yaml
  - path: dnsresolver_env_patch.yaml
  - path: contentwriter_env_patch.yaml
  - path: robotsevaluator_env_patch.yaml
  - path: harvester_env_patch.yaml
  - path: warcvalidator_env_patch.yaml
  - path: warcvalidator_volume_patch.yaml

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

secretGenerator:
  - name: veidemann-ingress-tls-cert
    type: kubernetes.io/tls
    files:
      - tls.key=cert/veidemann-local_key.pem
      - tls.crt=cert/veidemann-local_cert.pem
  - name: veidemann-rethinkdb-env
    literals:
      - DB_USER=admin
      - DB_PASSWORD=rethinkdb
  - name: rethinkdb
    behavior: replace
    literals:
      - rethinkdb-password=rethinkdb

configMapGenerator:
  - name: veidemann
    files:
      - log4j2.xml
    literals:
      - oosHandler_host=veidemann-ooshandler
      - openidConnectIssuer=https://veidemann.local/dex

vars:
  # Get service names.
  - name: DB_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: rethinkdb-proxy
  - name: CONTROLLER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-controller
  - name: FRONTIER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-frontier
  - name: ROBOTS_EVALUATOR_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-robotsevaluator-service
  - name: DNS_RESOLVER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-dns-resolver
  - name: CONTENT_WRITER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-contentwriter
  - name: CACHE_BALANCER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-cache-balancer
  - name: CACHE_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-cache
  - name: HARVESTER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-harvester
  - name: OOS_HANDLER_SERVICE_NAME
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: veidemann
    fieldref:
      fieldpath: data.oosHandler_host
