apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rethinkdb-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: veidemann-backup
              emptyDir: # unset emptyDir from base
