apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../dev/veidemann

patches:
  # Kind's pv provisioner doesn't support ReadWriteMany
  # This patch updates all pvc's in namespace veidemann to ReadWriteOnce
  - patch: |-
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: Name does not matter
      spec:
        accessModes:
          - ReadWriteOnce
    target:
      kind: PersistentVolumeClaim
      version: v1
      namespace: veidemann

patchesStrategicMerge:
  - kind_ip_patch.yaml

