---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: veidemann-warcs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: veidemann-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
