apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: veidemann-dns-resolver
    options:
      # disable so we can reload the configuration without restarting the pod
      disableNameSuffixHash: true
    files:
      - Corefile
