apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/instance: veidemann-controller
  app.kubernetes.io/part-of: veidemann

configMapGenerator:
  - name: veidemann-controller-envoy
    files:
      - envoy.yaml
  - name: veidemann-controller
    files:
      - log4j2.xml

secretGenerator:
  - name: veidemann-controller
    options:
      disableNameSuffixHash: true
    literals:
      - apiKeyRoleMapping.txt=ABCD-1234 ADMIN
