apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: veidemann-controller
  app.kubernetes.io/instance: veidemann-controller
  app.kubernetes.io/part-of: veidemann
  app.kubernetes.io/component: veidemann-controller

configmapGenerator:
  - name: veidemann-controller-envoy
    files:
      - envoy.yaml

secretGenerator:
  - literals:
      - DB_USER=admin
      - DB_PASSWORD=rethinkdb
    name: veidemann-rethinkdb-env
