apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/rethinkdb-backup

patchesStrategicMerge:
  - schedule_patch.yaml
  - volume_patch.yaml
  - env_patch.yaml
