apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-cluster
  labels:
    app.kubernetes.io/component: cluster
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 29015
      targetPort: cluster
  selector:
    app.kubernetes.io/component: cluster
