apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-log-service
spec:
  template:
    spec:
      containers:
        - name: veidemann-log-service
          env:
            - name: DB_HOST
              value: "scylla-client"
