apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/veidemann-log-service

patchesStrategicMerge:
  - schema_job_env_patch.yaml
  - deployment_env_patch.yaml
