apiVersion: batch/v1
kind: Job
metadata:
  name: veidemann-log-schema
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: veidemann-log-schema
          image: norsknettarkiv/veidemann-log-schema:v1.0.0
          env:
            - name: SCYLLA_HOST
              value: scylla
