apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-proxy
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  ports:
    - port: 28015
      targetPort: driver
  selector:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: proxy
