apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - surgery-cronjob.yaml

secretGenerator:
  - name: surgery
    literals:
      - VEIDEMANN_API_KEY=""

configMapGenerator:
  - name: surgery
    files:
      - surgery.sh
