apiVersion: v1
kind: Service
metadata:
  name: veidemann-log-service
  labels:
    app.kubernetes.io/name: veidemann-log-service
    app.kubernetes.io/component: log-service
    metrics: prometheus
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
      protocol: TCP
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-log-service
    app.kubernetes.io/component: log-service
