apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
    metrics: prometheus
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: intra
      port: 7000
      targetPort: intra
    - name: tls
      port: 7001
      targetPort: tls
    - name: jmx
      port: 7199
      targetPort: jmx
    - name: cql
      port: 9042
      targetPort: cql
    - name: thrift
      port: 9160
      targetPort: thrift
  selector:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
