apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cassandra-servicemonitor
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - path: /metrics
      port: http-metrics
  selector:
    matchLabels:
      metrics: prometheus
  namespaceSelector:
    matchNames:
      - observability
