apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
spec:
  serviceName: cassandra
  selector:
    matchLabels:
      app.kubernetes.io/name: cassandra
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cassandra
        app.kubernetes.io/component: database
    spec:
      volumes:
        - name: data
          emptyDir: {}
      terminationGracePeriodSeconds: 30
      containers:
        # Cassandra
        - name: cassandra
          image: cassandra:3.11.5
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: 9042
            - name: thrift
              containerPort: 9160
          volumeMounts:
            - name: data
              mountPath: /var/lib/cassandra
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MAX_HEAP_SIZE
              value: "2048M"
            - name: HEAP_NEWSIZE
              value: "1024M"
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.default.svc.cluster.local"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: "GossipingPropertyFileSnitch"
            - name: CASSANDRA_DC
              value: "dc1"
            - name: CASSANDRA_CLUSTER_NAME
              value: "cassandra"
            - name: CASSANDRA_RACK
              value: "rac1"
            - name: CASSANDRA_START_RPC
              value: "false"
          livenessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nodetool status" ]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5

        # Cassandra exporter
        - name: cassandra-exporter
          image: criteord/cassandra_exporter:2.2.1
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 45
