apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  template:
    spec:
      containers:
        - name: cassandra
          env:
            - name: CASSANDRA_SEEDS
              value: "$(NAME)-0.$(NAME).$(NAMESPACE).svc.cluster.local"
