apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:

  - ../../../bases/veidemann-warcvalidator

patchesStrategicMerge:
  - warcvalidator_volume_patch.yaml
  - warcvalidator_env_patch.yaml
