apiVersion: v1
kind: Service
metadata:
  name: veidemann-ooshandler
  labels:
    app.kubernetes.io/name: veidemann-ooshandler
    app.kubernetes.io/component: ooshandler
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50052
      targetPort: http-ooshandler
    - name: http-metrics
      port: 9301
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-ooshandler
    app.kubernetes.io/component: ooshandler
