apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: veidemann-cache
  labels:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache
spec:
  serviceName: veidemann-cache
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-cache
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-cache
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: veidemann-cache
          image: norsknettarkiv/veidemann-cache:0.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          env:
            - name: DNS_SERVERS
              value: veidemann-dns-resolver
          volumeMounts:
            - name: workdir
              mountPath: /var/cache/squid
            - name: cache-certificate
              mountPath: "/ca-certificates"
              readOnly: true
        - name: veidemann-cache-exporter
          image: boynux/squid-exporter:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-metrics
              containerPort: 9301
              protocol: TCP
          args:
            - "-listen"
            - "0.0.0.0:9301"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: cache-certificate
          secret:
            secretName: veidemann-cache
        - name: workdir
          emptyDir: {}
