apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann

resources:
  - ../../../bases/veidemann-controller
  - controller_ingressroute.yaml

patchesStrategicMerge:
  - controller_env_patch.yaml
  - controller_ca_patch.yaml
